### ISSUE TITLE
Infografia 

### ISSUE THREAD

**Issue by bg55-a** [SistemasTecTlaxiaco/actividad-1-infografia-de-gestion-de-proyectos-de-software-bg55-a#2]
![Infografía de Gestión de Proyectos de Software_001](https://user-images.githubusercontent.com/67558921/186510346-48d9a053-a5bf-47bb-b757-b8584f18275c.png)

**Comment by Abraham890** [comment]
Calificación: 20 Puntos

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
