### ISSUE TITLE
Infografia

### ISSUE THREAD

**Issue by bg55-a** [SistemasTecTlaxiaco/actividad-1-infografia-de-gestion-de-proyectos-de-software-bg55-a#3]
[Infografía de Gestión de Proyectos de Software.pdf](https://github.com/SistemasTecTlaxiaco/actividad-1-infografia-de-gestion-de-proyectos-de-software-bg55-a/files/12457866/Infografia.de.Gestion.de.Proyectos.de.Software.pdf)

**Comment by JoseABCruz** [comment]
Calificación: 19.6%

**Comment by josealfredo79** [comment]
Bien hecho y revisado..
